### ISSUE TITLE
Interrupting Permissions flow crashes on next launch

### ISSUE THREAD

**Issue by spaceLenny** [UncorkedStudios/tunnelvision#1]
if you leave and revoke permissions and come back it crashes because it doesn't check if you have permissions in onResume (currently only checks in splash screen in initial onCreate)

**Comment by spaceLenny** [comment]
Unable to repro this on Pixel XL

**Comment by katmitchell** [comment]
Still seeing this on the Pixel 2 XL.

1. Open app and accept permissions. Note everything is working correctly.
2. Hit "home" button to go to the launcher
3. Long press on application icon and open settings. Remove all permissions.
4. Tap app icon again. Note crash.

```10-01 08:00:34.282 9478-9478/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.androidexperiments.tunnelvision, PID: 9478
    java.lang.RuntimeException: Unable to resume activity {com.androidexperiments.tunnelvision/com.androidexperiments.tunnelvision.MainActivity}: java.lang.RuntimeException: setAudioSource failed.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: setAudioSource failed.
        at android.media.MediaRecorder.setAudioSource(Native Method)
        at com.uncorkedstudios.android.view.recordablesurfaceview.RecordableSurfaceView.initRecorder(RecordableSurfaceView.java:247)
        at com.androidexperiments.tunnelvision.MainActivity.setReady(MainActivity.java:423)
        at com.androidexperiments.tunnelvision.MainActivity.onResume(MainActivity.java:332)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7107)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ```

**Comment by spaceLenny** [comment]
Ahhh makes sense. Didn't try this. Thanks.

**Comment by spaceLenny** [comment]
Fixed on master.
