### ISSUE TITLE
Crash when lock/unlock phone while running

### ISSUE THREAD

**Issue by spaceLenny** [UncorkedStudios/tunnelvision#3]
``` 09-28 11:27:12.420 14696-17389/com.androidexperiments.tunnelvision E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.androidexperiments.tunnelvision, PID: 14696
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at com.androidexperiments.shadercam.gl.VideoRenderer.onDrawFrame(VideoRenderer.java:553)
        at com.androidexperiments.tunnelvision.gl.SlitScanRenderer.onDrawFrame(SlitScanRenderer.java:160)
        at com.uncorkedstudios.android.view.recordablesurfaceview.RecordableSurfaceView$ARRenderThread.run(RecordableSurfaceView.java:516)```

**Comment by spaceLenny** [comment]
assuming this is an onPause lifecycle issue.

**Comment by katmitchell** [comment]
`09-28 11:28:33.706 17501-17551/com.androidexperiments.tunnelvision E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -19
09-28 11:28:33.964 17501-17717/com.androidexperiments.tunnelvision E/GLConsumer: [SurfaceTexture-1-17501-0] checkAndUpdateEglState: invalid current EGLContext
09-28 11:28:33.965 17501-17717/com.androidexperiments.tunnelvision E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.androidexperiments.tunnelvision, PID: 17501
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at com.androidexperiments.shadercam.gl.VideoRenderer.onDrawFrame(VideoRenderer.java:553)
        at com.androidexperiments.tunnelvision.gl.SlitScanRenderer.onDrawFrame(SlitScanRenderer.java:160)
        at com.uncorkedstudios.android.view.recordablesurfaceview.RecordableSurfaceView$ARRenderThread.run(RecordableSurfaceView.java:516)`

A few extra lines, because they're relevant and I forgot them before.

**Comment by spaceLenny** [comment]
Fixed
